name: Go checks, tests and release

on: push
jobs:
  go-pipeline:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
    - name: go1.13 linter
      uses: shoukoo/golang-pipeline/go1.13/linter@master
      with:
        STATICCHECK: on
        GOLINT: on
        GOLINTPATH: github.com/interlock/dynamic-route53
        MISSPELL: on
        ERRCHECK: on
    - name: go1.13 test
      uses: shoukoo/golang-pipeline/go1.13/test@master
    - name: osx build
      uses: shoukoo/golang-pipeline/go1.12/release@master
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: darwin
        GOARCH: amd64
    - name: windows build
      uses: shoukoo/golang-pipeline/go1.12/release@master
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: windows
        GOARCH: amd64
    - name: linux build amd64
      uses: shoukoo/golang-pipeline/go1.12/release@master
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: linux
        GOARCH: amd64
    - name: linux build arm
      uses: shoukoo/golang-pipeline/go1.12/release@master
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOS: linux
        GOARCH: arm

